// Cubetto Playset version number
#define PRIMO_CUBETTO_PLAYSET_VERSION "1.0"

////////////////////////////////////////////////////////////////////////////////

// The Interface can generate a stream of up to 16 movement commands.
// Each command is 1 of Forward, Left or Right.
// Stop has been assigned to 0x00 to cover any empty slots in an Interface.
// One byte has been used for each movement command.
// This allows extra space for future meta-data (e.g. position ordinal),
// or extra commands (e.g. BACK, 45TURN etc).
#define PRIMO_COMMAND_STOP    0x00
#define PRIMO_COMMAND_FORWARD 0x01
#define PRIMO_COMMAND_LEFT    0x02
#define PRIMO_COMMAND_RIGHT   0x03

////////////////////////////////////////////////////////////////////////////////

// This 32-bit value is the identifier for ANY Cubetto Playset.  It is inserted
// into every radio packet sent by ANY Interface.  A check is made on every
// radio packet, received by ANY Cubetto Robot, that this value is present.
#define PRIMO_ID 0xDE1D8758

// Single radio pipe address for the 2 nodes to communicate.
const uint64_t pipe = 0xE8E8F0F0E1LL;

// This 32-bit value is randomly generated by a particular Interface every time it powers-up.
// It is inserted into every radio packet sent by that Interface.
// Cubetto Robot uses this value to pair to that Interface.
static long sessionId = 0;

static uint32_t ackMessageCount = 0;

// The nRF24l01 can accept up to 32 bytes in a single radio packet,
// The comms protocol is designed to encapsulate a complete set of Cubetto Playset movement commands
// in one packet along with an identifier for all Interfaces, and a unique identifier for this Interface.
#define PRIMO_NRF24L01_MAX_PACKET_SIZE 32
static char packet[PRIMO_NRF24L01_MAX_PACKET_SIZE];

